name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Execute Gradle build
      run: ./gradlew build
