name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Execute Gradle build
      run: ./gradlew :javaparser-runner:jar
    - name: Set version
      run: |
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Upload to GitHub Releases
      if: "!contains(github.ref_name, 'pre')"
      run: gh release create --title ${{ github.ref_name }} --generate-notes ${{ github.ref_name }} ./javaparser-runner/build/libs/javaparser-${VERSION}.jar
    - name: Upload to GitHub Releases for pre-release
      if: "contains(github.ref_name, 'pre')"
      run: gh release create --title ${{ github.ref_name }} --generate-notes --prerelease ${{ github.ref_name }} ./javaparser-runner/build/libs/javaparser-${VERSION}.jar
